import { FileSource } from "./file-source";
import { HierarchyLevel } from "./hierarchy-level";
import { Project } from "./project";
import { SiteEventInfo } from "./site-eventInfo";
import { SiteEventPropertyInfo } from "./site-event-property-info";
import { SitePatientPropertyInfo } from "./site-patient-property-info";
import { User } from 'core/lib/models/UserInfo';

export class UserSession {
    public sessionId: number;
    public filterPatientProp1: number;
    public filterPatientProp1Condition: string;
    public filterPatientProp1Value: string;
    public filterPatientProp2: number;
    public filterPatientProp2Condition: string;
    public filterPatientProp2Value: string;
    public fromDateEvents: Date;
    public sessionInfo: string;
    public sessionName: string;
    public openTime: Date;
    public modificationTime: Date;
    public pivotEventTimeField: string;
    public pivotFirstLast: string;
    public pivotTimeAggregationLevel: string;
    public pivotOccurrence: number;
    public useFileAsSource: boolean;
    public sourceFileId: number;
    public status: string;
    public toDateEvents: Date;
    public userBirthAsPivot: boolean;
    public pivotEventId: number;
    public projectId: number;
    public userId: number;
    public hierarchyLevelIdP1: number;
    public hierarchyLevelIdP2: number;
    public pivotFromAge: number;
    public pivotToAge: number;
    public changeLog: string;
    public functionP1: string;
    public functionP2: string;
    public filterEventId: number;
    public filterEventPropertyField: string;
    public filterCondition: string;
    public filterConditionValue: string;
    public filterFromAge: number;
    public filterToAge: number;
    public filterNumberOfEventsForPatient: number;
    public filterHierarchyLevelId: number;
    public filterDocumentType: string;
    public pivotEventMinMaxPropertyField: string;
    public cohortModificationTime: Date;
    public cohortStatus: string;
    public cohortSize: number;
    public notificationBookmark: number;
    public patientPropModificationTime: Date;
    public project: Project;
    public user: User;
    public siteEventPropertyInfo: SiteEventPropertyInfo;
    public fileSource: FileSource;
}
